'use client';
import { useState, useEffect } from 'react';
import axios from 'axios';
import { linkedinConfig } from '../linkedin.config';
import EmojiPicker from 'emoji-picker-react';
import { EmojiClickData } from 'emoji-picker-react';

const PageLinkedin = () => {

    return (
        <div className="bg-muted">
            <div className="container px-8 py-8">

                <div className='flex justify-between flex-col  w-full gap-10 sm:flex-row'>
                    <div className='w-full'>
                        <h2 className="text-2xl lg:text-2xl font-bold mb-4 ">How to Generate Post Using AI?</h2>
                        <ol className="relative text-gray-500 border-s border-gray-200 dark:border-gray-700 dark:text-gray-400 pt-2">
                            <li className="mb-10 ms-6">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-green-200 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-green-900">
                                    <svg className="w-3.5 h-3.5 text-green-500 dark:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                        <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 5.917 5.724 10.5 15 1.5" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">What is your post about?</h3>
                                <p className="text-sm">Input Field: This section allows users to enter the topics or keywords related to their LinkedIn post. The example in the screenshot shows keywords such as "Digital Marketing, Social Media, Content Marketing, Branding."</p>
                            </li>
                            <li className="mb-10 ms-6">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-gray-100 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-gray-700">
                                    <svg className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16">
                                        <path d="M18 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2ZM6.5 3a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5ZM3.014 13.021l.157-.625A3.427 3.427 0 0 1 6.5 9.571a3.426 3.426 0 0 1 3.322 2.805l.159.622-6.967.023ZM16 12h-3a1 1 0 0 1 0-2h3a1 1 0 0 1 0 2Zm0-3h-3a1 1 0 1 1 0-2h3a1 1 0 1 1 0 2Zm0-3h-3a1 1 0 1 1 0-2h3a1 1 0 1 1 0 2Z" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">Keyword</h3>
                                <p className="text-sm">Input Field: Users can enter specific keywords they want to include in their post. This helps in refining the content generated by the AI.</p>
                            </li>
                            <li className="mb-10 ms-6">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-gray-100 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-gray-700">
                                    <svg className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
                                        <path d="M16 1h-3.278A1.992 1.992 0 0 0 11 0H7a1.993 1.993 0 0 0-1.722 1H2a2 2 0 0 0-2 2v15a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2Zm-3 14H5a1 1 0 0 1 0-2h8a1 1 0 0 1 0 2Zm0-4H5a1 1 0 0 1 0-2h8a1 1 0 1 1 0 2Zm0-5H5a1 1 0 0 1 0-2h2V2h4v2h2a1 1 0 1 1 0 2Z" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">Language</h3>
                                <p className="text-sm">Dropdown Menu: Users can select the language in which they want the post to be generated. The screenshot shows "English" selected.</p>

                            </li>
                            <li className="ms-6 mb-10">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-gray-100 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-gray-700">
                                    <svg className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M16.412 0H3.588A3.588 3.588 0 0 0 0 3.588v12.824A3.588 3.588 0 0 0 3.588 20h12.824A3.588 3.588 0 0 0 20 16.412V3.588A3.588 3.588 0 0 0 16.412 0ZM6 17H4V7h2Zm-1-12.19a1.19 1.19 0 1 1 0-2.38 1.19 1.19 0 0 1 0 2.38ZM17 17h-2v-4.5c0-3.184-4-2.941-4 0V17H9V7h2v1.403C12.932 6.336 17 5.973 17 9.87V17Z" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">Tone</h3>
                                <p className="text-sm">Dropdown Menu: Users can select the tone of the post. Options might include formal, informal, professional, friendly, etc. The example shows "None" selected, indicating no specific tone preference.</p>
                            </li>
                            <li className="ms-6">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-gray-100 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-gray-700">
                                    <svg className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M16.412 0H3.588A3.588 3.588 0 0 0 0 3.588v12.824A3.588 3.588 0 0 0 3.588 20h12.824A3.588 3.588 0 0 0 20 16.412V3.588A3.588 3.588 0 0 0 16.412 0ZM6 17H4V7h2Zm-1-12.19a1.19 1.19 0 1 1 0-2.38 1.19 1.19 0 0 1 0 2.38ZM17 17h-2v-4.5c0-3.184-4-2.941-4 0V17H9V7h2v1.403C12.932 6.336 17 5.973 17 9.87V17Z" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">Generate AI Post</h3>
                                <p className="text-sm">Button: After entering the necessary details, users can click this button to generate the AI-based LinkedIn post. The AI will use the provided keywords, language, and tone to create a draft.</p>
                            </li>
                        </ol>
                    </div>
                    <div className='w-full'>
                        <h2 className="text-2xl lg:text-2xl font-bold mb-4 ">How to Share a post on LinkedIn using this tool?</h2>
                        <ol className="relative text-gray-500 border-s border-gray-200 dark:border-gray-700 dark:text-gray-400 pt-2">
                            <li className="mb-10 ms-6">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-green-200 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-green-900">
                                    <svg className="w-3.5 h-3.5 text-green-500 dark:text-green-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                        <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 5.917 5.724 10.5 15 1.5" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">Authentication</h3>
                                <p className="text-sm">Connect Linekdin: Users need to Connect with their LinkedIn account using OAuth</p>
                            </li>
                            <li className="mb-10 ms-6">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-gray-100 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-gray-700">
                                    <svg className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16">
                                        <path d="M18 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2ZM6.5 3a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5ZM3.014 13.021l.157-.625A3.427 3.427 0 0 1 6.5 9.571a3.426 3.426 0 0 1 3.322 2.805l.159.622-6.967.023ZM16 12h-3a1 1 0 0 1 0-2h3a1 1 0 0 1 0 2Zm0-3h-3a1 1 0 1 1 0-2h3a1 1 0 1 1 0 2Zm0-3h-3a1 1 0 1 1 0-2h3a1 1 0 1 1 0 2Z" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">Profile Information</h3>
                                <p className="text-sm">Fetch Profile: A fter successful authentication, fetch and display the user's LinkedIn profile information.</p>
                            </li>
                            <li className="mb-10 ms-6">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-gray-100 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-gray-700">
                                    <svg className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
                                        <path d="M16 1h-3.278A1.992 1.992 0 0 0 11 0H7a1.993 1.993 0 0 0-1.722 1H2a2 2 0 0 0-2 2v15a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2Zm-3 14H5a1 1 0 0 1 0-2h8a1 1 0 0 1 0 2Zm0-4H5a1 1 0 0 1 0-2h8a1 1 0 1 1 0 2Zm0-5H5a1 1 0 0 1 0-2h2V2h4v2h2a1 1 0 1 1 0 2Z" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">Post Creation</h3>
                                <p className="text-sm">Text Input: A textarea for users to enter their post content.</p>
                                <p className="text-sm">File Upload: An option for users to upload images or videos for their post.</p>
                                <p className="text-sm">Emoji Picker: An emoji picker to add emojis to the post.</p>
                            </li>
                            <li className="ms-6">
                                <span className="absolute flex items-center justify-center w-8 h-8 bg-gray-100 rounded-full -start-4 ring-4 ring-white dark:ring-gray-900 dark:bg-gray-700">
                                    <svg className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M16.412 0H3.588A3.588 3.588 0 0 0 0 3.588v12.824A3.588 3.588 0 0 0 3.588 20h12.824A3.588 3.588 0 0 0 20 16.412V3.588A3.588 3.588 0 0 0 16.412 0ZM6 17H4V7h2Zm-1-12.19a1.19 1.19 0 1 1 0-2.38 1.19 1.19 0 0 1 0 2.38ZM17 17h-2v-4.5c0-3.184-4-2.941-4 0V17H9V7h2v1.403C12.932 6.336 17 5.973 17 9.87V17Z" />
                                    </svg>
                                </span>
                                <h3 className="font-bold leading-tight">Publish Post</h3>
                                <p className="text-sm">Button: Once the post content and image (if any) are ready, users can click this button to publish their post on LinkedIn.</p>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default PageLinkedin;
